### PR TITLE
Capture parser errors using xmlCtxtGetLastError

### LINKED ISSUE #52: Capturing parser errors programmatically
Hi,

I can currently see detailed errors generated by libxml in stdout, but I need to suppress this output and capture the errors programmatically. Is there a way to do this at present?

e.g. I want to capture error detail such as the following in the `error` object returning from `Parse` :

```
Entity: line 1: parser error : Start tag expected, '<' not found
invalid
^
```

### PR DESCRIPTION
**Pull request by the4thamigo-uk**
fixes #52

### CODE REVIEW

**Comment by lestrrat** [comment]
I have a feeling you need to release the `*xmlError` struct somewhere?

**Comment by the4thamigo-uk** [comment]
Ah ok, but do you also have this problem then in `XMLC14NDocDumpMemory`

**Comment by lestrrat** [comment]
Also, I agree that having this is better than not, but can you please note in the comment somewhere that in the future, we should probably be formatting the error message in C land, and not in Go (and therefore use `xmlParserError` or some other function that I may have overlooked).

If we can just fetch the error message from C, and worry about that alone, I think it's much better than mucking with C structs (i.e. `xmlError`) in Go land

**Comment by lestrrat** [comment]
> Ah ok, but do you also have this problem then in XMLC14NDocDumpMemory

Well, then you might have found another memory bug :)

**Comment by the4thamigo-uk** [comment]
Not sure though, because no copy is made when returning, so I think it is correct not to free it :

https://github.com/GNOME/libxml2/blob/35e83488505d501864826125cfe6a7950d6cba78/error.c#L924

**Comment by lestrrat** [comment]
Oh interesting. Thanks for the pointer! Yeah, that looks like it belongs in the context. Can you keep a note of this in the comment too? I'm sure I'm going to scratch my head in the future on the same line :D

**Comment by the4thamigo-uk** [comment]
Updated the commit comment as requested.

**Comment by lestrrat** [comment]
Well, I think for the time being this should suffice:

* unexport https://github.com/lestrrat-go/libxml2/pull/53/files#diff-be30cb2d50c6139b29edc9d73078f9d8R518
* format the return value from the `ParseXXX` function just like what you would see in stdout.

If I were the end user, I think I'd expect the `GetLastError` function to return a wrapper (or some copy) of the underlying `*xmlError` structure. So I think that function should return a struct. But the parser function can return whatever, really.

**Comment by the4thamigo-uk** [comment]
Yup ok, will do

**Comment by the4thamigo-uk** [comment]
Have updated the commit.

P.S. the error message 'failed to document' in the existing code doesnt mean a lot to me. How are you meant to interpret that as a user of the library?

**Comment by lestrrat** [comment]
That's probably one of those cut n paste (then a mass replace) things that got left over. Feel free to fix that in this PR or send me an issue so I don't forget :)

**Comment by the4thamigo-uk** [comment]
Oh shall I move the xmlCtxtLastError function to be near to `ReportErrors`?

**Comment by lestrrat** [comment]
You mean physical placement? I really have no preference there. Your call.

**Comment by lestrrat** [comment]
Well, I have to go take care of the kids now. Let me know when you finish the PR, and I will merge later. Thanks for your contribution!

**Comment by the4thamigo-uk** [comment]
Ok I moved it. Think its done, so long as it passes checks.

**Pull request merged**
