### PR TITLE
Remove warns in clib.go

### PR DESCRIPTION
**Pull request by zapisanchez**
C does not have an implicit conversion from const-qualified pointer types to non-const-qualified ones, so you should add an explicit one

### CODE REVIEW

**Comment by lestrrat** [comment]
@zapisanchez I'm sure what you are suggesting is correct, but a simple go test / build on my environment does not reproduce the warning. Can you describe why that is? I (belated) added a CI environment in GitHub Actions for this repository just now so you know what I do to check.

**Comment by zapisanchez** [comment]
With a simple go test under arch linux this warns appears:

go test ./...  
`
# github.com/lestrrat-go/libxml2/clib
/home/zapi/go/pkg/mod/github.com/lestrrat-go/libxml2@v0.0.0-20231123112539-c64e12f1f967/clib/clib.go: In function ‘MY_xmlLastError’:
/home/zapi/go/pkg/mod/github.com/lestrrat-go/libxml2@v0.0.0-20231123112539-c64e12f1f967/clib/clib.go:61:16: warning: return discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   61 |         return xmlGetLastError();
      |                ^~~~~~~~~~~~~~~~~
/home/zapi/go/pkg/mod/github.com/lestrrat-go/libxml2@v0.0.0-20231123112539-c64e12f1f967/clib/clib.go: In function ‘MY_xmlCtxtLastError’:
/home/zapi/go/pkg/mod/github.com/lestrrat-go/libxml2@v0.0.0-20231123112539-c64e12f1f967/clib/clib.go:67:16: warning: return discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   67 |         return xmlCtxtGetLastError(ctx);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~`

I Bet this is for the same than last problem, my arch is using latest version of libxml-2
image

**Comment by lestrrat** [comment]
Awwww, ubuntu doesn't have a deb for 2.12...
Can you please come up with a CI workflow to install the version you want, and then run `go test`.  I know it's a minor task that I can do but I'm currently not all that motivated, so would appreciate it if you could come up with the repro in CI yourself

**Comment by zapisanchez** [comment]
Hi @lestrrat I Have done a small refactor:

- added go modules (go mod and o sum)
- refactor due go mod
- fix some lintings
- Added actions it fails because we need this code merged in master of original branch in order to test)

I have tested in local and everything passed as usual
image


I know that's a big change. 
I've not made changes on business logic
I've tried to make minor changes 

It is not my intention to change your code, just to help you update it and clean it up. :D

**Comment by lestrrat** [comment]
@zapisanchez I'm very sorry, but I can't accept your PR as is. I don't claim that my code is better by any means, but I can't accept a PR that contains various different all jumbled into one :(

I have created #93 to apply your warnings fix and CI env. I haven't merged it in case you wanted credit for your work -- if you do, please create a PR with your commits that only contain what's on #93.

**Comment by zapisanchez** [comment]
@lestrrat NP, you can merge #93 PR :+1:

**Comment by zapisanchez** [comment]
@lestrrat otherwise, i recommend update the code to use go modules and make linting cleanup

**Comment by lestrrat** [comment]
@zapisanchez but I already did that in #92...?

**Comment by lestrrat** [comment]
closed by #93

**Pull request closed without merging**
